spring:
  profiles:
    active:
    - dev
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: application-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource             # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver               # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01               # 数据库名称
    username: root
    password: sa
    dbcp2:
      min-idle: 5
      initial-size: 5                                        # 数据库连接池的最小维持连接数
      max-total: 5                                           # 初始化连接数
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml         # mybatis配置文件所在位置
  type-aliases-package: com.atguigu.springcloud.entities     # 所有entity别名所在包
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml    
eureka:
  client:  #客户端注册eureka服务列表
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001
    prefer-ip-address: true  #访问路径可以显示ip
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguige.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring:
   profiles: test  #为客户端提供不同的连接方式
   application:
    name: microservicecloud-config-dept-client
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb02
    username: root
    password: sa
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis所在路径
  type-aliases-package: com.lei.springcloud.entities #entity别名类
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml #mapper映射文件
      
eureka:
  client: #客户端注册进eureka服务列表内 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
      
info:
  app.name: atguigu-microservicecloud-springcloud-springcloudconfig01
  company.name: www.lei.com
  build.artifactId: ${project.artifactId}$
  build.version: ${project.version}$    